application: gosoursite
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /admin/.*
  script: admin.app
  login:  admin 

- url: /.*
  script: mySite.app
